site_name: RETRO CARNAGE
site_url: http://docs.retro-carnage.net/
nav:
  - Home: index.md
  - Game: game.md
  - Backend: backend.md
  - Editor: editor.md
  - License: license.md
theme:
  name: material
extra:
  generator: false
copyright: Copyright &copy; 2020 - 2022 Thomas Werner